### ISSUE TITLE
Rotacion de display

### ISSUE THREAD

**Issue by vtedescoe** [danidask/MatrizLed#2]
Estimados,
Se podrá implementar la rotación de los display?
Estoy usando este modulo https://articulo.mercadolibre.com.ar/MLA-759130381-modulo-display-4-digitos-azul-matriz-leds-max7219-nubbeo-_JM?quantity=1
Y cuando lo programo quedan rotados.

![WhatsApp Image 2019-04-24 at 14 23 27](https://user-images.githubusercontent.com/13407742/56679984-a626c200-669c-11e9-81ba-cab786ea2dfb.jpeg)

Gracias por tu tiempo.

Saludos,

**Comment by danidask** [comment]
Implementado "rotar" en version 2.0.4
