### ISSUE TITLE
Desplazarse y rotacion de display

### ISSUE THREAD

**Issue by sebaz28** [danidask/MatrizLed#3]
Buenos dias,

Cuando "rotar = true" el desplazamiento permanece vertical.
¿Cómo podemos arreglarlo?
Gracias

seb
![IMG_20191221_191530](https://user-images.githubusercontent.com/59122383/71312041-c7f06880-2426-11ea-9c73-b78bdbe71a72.jpg)

**Comment by danidask** [comment]
Solucionado en version 2.0.5

**Comment by sebaz28** [comment]
Buenos dias,
Gracias por la corrección, pero todavía hay un problema.
Ahora la función "pantalla.escribirFrase (" Hola ");" no se muestra correctamente
![IMG_20191223_083049](https://user-images.githubusercontent.com/59122383/71343447-29682280-2560-11ea-98d7-24cce04637e3.jpg)

La función "pantalla.escribirFraseScroll (" Hola ", 50);" Tampoco funciona.
![IMG_20191223_082721_004](https://user-images.githubusercontent.com/59122383/71343469-3d138900-2560-11ea-98ff-c9879fad356b.jpg)

No entiendo por qué el LED ("dispositivo 0, fila 0, columna 0") está aquí.
![IMG_20191223_083121](https://user-images.githubusercontent.com/59122383/71343518-63d1bf80-2560-11ea-8e35-6659e0387a2d.jpg)


Dado que el dispositivo 0 está en el lado del conector, ¿no debería girarse la pantalla hacia el otro lado?
![IMG_20191223_082017](https://user-images.githubusercontent.com/59122383/71343645-c4f99300-2560-11ea-8976-701d37ecfdb5.jpg)


Atentamente
Sebastián
